#!/usr/bin/env python3
"""Set up DevOps AI skills and MCP catalog configs for common coding agents.

Supported workspace clients:
- Claude Code: CLAUDE.md + .mcp.json
- OpenAI Codex: AGENTS.md + .codex/mcp.json
- Cursor: .cursor/rules/awesome-agentic-devops.mdc + .cursor/mcp.json
- Google Antigravity: AGENTS.md + .antigravity/mcp.json
- VS Code: .vscode/mcp.json

The utility is intentionally safe-by-default: it writes a local catalog MCP
server that exposes the repo's official DevOps/SRE/Cloud MCP catalog for search
and review. It does not install third-party MCP servers, mutate cloud resources,
or write secrets.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml

SUPPORTED_CLIENTS = ("claude-code", "codex", "cursor", "antigravity", "vscode")
CATALOG_PATH = Path("devops-ai/official-devops-mcp-catalog.json")
SKILL_PATH = Path("devops-ai/DEVOPS_SKILL.md")
GUIDE_PATH = Path("devops-ai/README.md")
SERVER_SCRIPT = Path("scripts/devops_catalog_mcp_server.py")

CLIENT_MCP_PATHS = {
    "claude-code": Path(".mcp.json"),
    "codex": Path(".codex/mcp.json"),
    "cursor": Path(".cursor/mcp.json"),
    "antigravity": Path(".antigravity/mcp.json"),
    "vscode": Path(".vscode/mcp.json"),
}


def load_repo_entries(repo_root: Path) -> list[dict[str, Any]]:
    with (repo_root / "data/repos.yaml").open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, list):
        raise SystemExit("data/repos.yaml must contain a list")
    return data


def official_devops_mcp_entries(entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    filtered = []
    for entry in entries:
        category = str(entry.get("category", ""))
        type_ = str(entry.get("type", ""))
        framework = str(entry.get("framework", ""))
        if not category.startswith("official-"):
            continue
        if "mcp" not in (category + " " + type_ + " " + framework).lower():
            continue
        filtered.append(entry)
    return sorted(filtered, key=lambda e: (str(e.get("category", "")), str(e.get("name", "")).lower()))


def mcp_config(repo_root: Path) -> dict[str, Any]:
    # Keep committed configs portable. Most editor/agent clients launch MCP
    # servers with the workspace as cwd; users who need absolute paths can rerun
    # the setup command from their target workspace.
    return {
        "mcpServers": {
            "awesome-agentic-devops-catalog": {
                "command": "python3",
                "args": [str(SERVER_SCRIPT), "--catalog", str(CATALOG_PATH)],
                "env": {},
            }
        }
    }


def skill_markdown(entries: list[dict[str, Any]]) -> str:
    categories = sorted({str(e.get("category", "unknown")) for e in entries})
    sample_rows = "\n".join(
        f"| [{e.get('name')}]({e.get('url')}) | {e.get('category')} | {e.get('action_level')} | {e.get('maturity')} | {e.get('operator_note')} |"
        for e in entries[:12]
    )
    category_lines = "\n".join(f"- `{category}`" for category in categories)
    return f"""# DevOps AI Operating Skill

Use this workspace as an operator-grade DevOps/SRE/Cloud MCP catalog and build lab.

## Safety rules

- Prefer read-only and proposal-mode workflows before any write-capable tool.
- Never paste secrets, tokens, kubeconfigs, cloud credentials, or private logs into model context.
- Require a human approval gate for deploys, Terraform applies, incident mutations, identity changes, and production writes.
- Preserve evidence: link PRs, plans, CI logs, traces, runbooks, and incident timelines.
- Treat catalog labels as a first-pass risk signal, not a production approval.

## MCP catalog tool

This setup registers a local MCP server named `awesome-agentic-devops-catalog`.
Use it to search official DevOps MCP entries before recommending integrations.

Suggested prompts:

- Search the DevOps MCP catalog for Terraform/IaC tools and compare blast radius.
- Find official observability MCP servers with audit or tracing evidence.
- List write-capable CI/CD or GitOps tools and explain required approval gates.
- Recommend a read-only starting point for Kubernetes/SRE investigation.

## Included official MCP categories

{category_lines}

## Sample entries

| Entry | Category | Action level | Maturity | Operator note |
| --- | --- | --- | --- | --- |
{sample_rows}
"""


def guide_markdown(entries: list[dict[str, Any]]) -> str:
    return f"""# DevOps AI Client Bootstrap

Generated by `scripts/setup_devops_ai_clients.py`.

This folder contains a local, dependency-light MCP catalog server and DevOps operating skill for:

- Claude Code
- OpenAI Codex
- Cursor
- Google Antigravity
- VS Code

## One-command setup

From the repository root:

```bash
python3 scripts/setup_devops_ai_clients.py --clients all --write
```

The command writes project-local config only. It does not install third-party MCP servers, mutate global settings, or store secrets.

## What is configured

- `devops-ai/official-devops-mcp-catalog.json` — {len(entries)} official DevOps/SRE/Cloud MCP catalog entries extracted from `data/repos.yaml`.
- `devops-ai/DEVOPS_SKILL.md` — shared operating instructions for AI coding agents.
- `scripts/devops_catalog_mcp_server.py` — tiny stdio MCP server exposing catalog search tools.
- Client config files such as `.mcp.json`, `.cursor/mcp.json`, `.vscode/mcp.json`, `.codex/mcp.json`, and `.antigravity/mcp.json` depending on selected clients.

## Supported MCP tools

- `search_devops_mcp_catalog` — search by keyword/category.
- `get_devops_mcp_entry` — return one scored catalog entry by name.

## Production safety

This setup intentionally exposes the catalog, not your cloud accounts. To connect a real official MCP server, first review its catalog entry for:

- `action_level`
- `human_approval`
- `evidence_tracing`
- `risk_notes`
- credential scope and blast radius

Add real server credentials only through each client or platform's secure secret mechanism.
"""


def claude_md() -> str:
    return """# Claude Code DevOps Skill

Load `devops-ai/DEVOPS_SKILL.md` before DevOps, SRE, Cloud, Kubernetes, Terraform, CI/CD, observability, or security-agent work in this repository.

Use the `awesome-agentic-devops-catalog` MCP server to search official MCP options before suggesting integrations. Prefer read-only/proposal workflows and require human approval for write-capable operations.
"""


def agents_md() -> str:
    return """# Agent Instructions

For Codex, Antigravity, and other coding agents in this workspace:

1. Read `devops-ai/DEVOPS_SKILL.md` first.
2. Use the local `awesome-agentic-devops-catalog` MCP server for official DevOps MCP discovery.
3. Never assume a write-capable MCP server is safe just because it is official.
4. Keep Terraform applies, deploys, incident mutations, identity changes, and production writes behind human approval.
"""


def cursor_rule() -> str:
    return """---
description: Operator-grade DevOps MCP and agent workflow guidance
alwaysApply: true
---

Read `devops-ai/DEVOPS_SKILL.md` before DevOps/SRE/Cloud work. Use the `awesome-agentic-devops-catalog` MCP server to compare official MCP servers by action level, approval gates, tracing evidence, maturity, and risk notes. Never expose secrets or bypass human approval for production writes.
"""


def write_text(path: Path, content: str, force: bool, writes: list[str]) -> None:
    if path.exists() and not force:
        writes.append(f"skip existing {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    writes.append(f"write {path}")


def write_json(path: Path, payload: Any, force: bool, writes: list[str]) -> None:
    write_text(path, json.dumps(payload, indent=2, ensure_ascii=False) + "\n", force, writes)


def selected_clients(raw: list[str]) -> list[str]:
    if raw == ["all"] or "all" in raw:
        return list(SUPPORTED_CLIENTS)
    unknown = sorted(set(raw) - set(SUPPORTED_CLIENTS))
    if unknown:
        raise SystemExit(f"Unknown clients: {', '.join(unknown)}. Supported: {', '.join(SUPPORTED_CLIENTS)}")
    return raw


def build_files(repo_root: Path, clients: list[str], force: bool, dry_run: bool) -> list[str]:
    entries = official_devops_mcp_entries(load_repo_entries(repo_root))
    writes: list[str] = []
    files: list[tuple[Path, str | dict[str, Any]]] = [
        (CATALOG_PATH, {"entries": entries}),
        (SKILL_PATH, skill_markdown(entries)),
        (GUIDE_PATH, guide_markdown(entries)),
    ]

    if "claude-code" in clients:
        files.append((Path("CLAUDE.md"), claude_md()))
    if "codex" in clients or "antigravity" in clients:
        files.append((Path("AGENTS.md"), agents_md()))
    if "cursor" in clients:
        files.append((Path(".cursor/rules/awesome-agentic-devops.mdc"), cursor_rule()))

    config = mcp_config(repo_root)
    for client in clients:
        files.append((CLIENT_MCP_PATHS[client], config))

    if dry_run:
        return [f"would write {path}" for path, _ in files]

    for path, content in files:
        absolute = repo_root / path
        if isinstance(content, dict):
            write_json(absolute, content, force, writes)
        else:
            write_text(absolute, content, force, writes)
    return writes


def main() -> int:
    parser = argparse.ArgumentParser(description="Set up DevOps AI skills and MCP catalog configs for Claude Code, Codex, Cursor, Antigravity, and VS Code.")
    parser.add_argument("--workspace", default=".", help="Repository/workspace root. Defaults to current directory.")
    parser.add_argument("--clients", nargs="+", default=["all"], help="Clients to configure: all, claude-code, codex, cursor, antigravity, vscode.")
    parser.add_argument("--write", action="store_true", help="Write files. Without this flag the command prints a dry run.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing generated files.")
    args = parser.parse_args()

    repo_root = Path(args.workspace).resolve()
    clients = selected_clients(args.clients)
    results = build_files(repo_root, clients, force=args.force, dry_run=not args.write)
    for result in results:
        print(result)
    if not args.write:
        print("dry run only; rerun with --write to create files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
